sudo: required
dist: bionic
language: c++
os: linux
compiler:
- gcc-4.8
before_install:
- sudo apt-get update
install:
- sudo apt-get install gcc-4.8
- sudo apt-get install g++-4.8
script:
- export TRAVIS_COMPILER=gcc-4.8
- export CC=${CC:-gcc-4.8}
- export CC_FOR_BUILD=${CC_FOR_BUILD:-gcc-4.8}
- export CXX=${CXX:-g++-4.8}
- export CXX_FOR_BUILD=${CXX_FOR_BUILD:-g++-4.8}
- ./bootstrap.sh
- ./configure
- make
